version: "3"
services:
  myelastic:
    image: hojatvb/my-elasticsearch-1:reyan1
    command: tail -F anything
    container_name: "myelastic"
    ports:
      - "9200:9200"
      - "5601:5601"
    networks:
      - default

  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
    volumes:
      - /var/lib/reyan-files/mongo/data:/data/db
    networks:
      - default

  reyan-api:
    hostname: reyan-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mymongodb
    volumes:
      - /var/lib/reyan-files:/mnt/reyan-files
    depends_on:
      - mymongodb
    networks:
      - default
      - nginx_web-server

networks:
  nginx_web-server:
    external:
      name: web-server-network