version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
    volumes:
      - /var/lib/reyan-files/mongo/data:/data/db

  reyan-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mymongodb
    volumes:
      - /var/lib/reyan-files:/mnt/reyan-files
    depends_on:
      - mymongodb